# Generated by Django 2.1 on 2019-07-12 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Paragráfo único com no máximo 100 palavras.', verbose_name='Resumo (Breve descrição)')),
                ('goal', models.TextField(verbose_name='Objetivo')),
                ('public', models.CharField(max_length=200, verbose_name='Público Alvo')),
                ('vacancies', models.PositiveIntegerField(verbose_name='Número Máximo de Participantes')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Pré-requisitos')),
                ('materials', models.TextField(blank=True, null=True, verbose_name='Recursos necessários')),
                ('workload', models.PositiveIntegerField(choices=[(1, '2 horas'), (2, '4 horas')], verbose_name='Carga Horária')),
                ('status', models.IntegerField(choices=[(1, 'Submetido'), (2, 'Aprovado'), (3, 'Não aprovado')], default=1, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_events', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('co_authors', models.ManyToManyField(blank=True, related_name='co_authors_events', to=settings.AUTH_USER_MODEL, verbose_name='Co-autores')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_events', to=settings.AUTH_USER_MODEL, verbose_name='Orientador')),
            ],
            options={
                'verbose_name': 'Minicurso',
                'verbose_name_plural': 'Minicursos',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Paragráfo único com no máximo 50 palavras.', verbose_name='Resumo (Breve descrição)')),
                ('goal', models.TextField(verbose_name='Objetivo')),
                ('status', models.IntegerField(choices=[(1, 'Submetido'), (2, 'Aprovado'), (3, 'Não aprovado')], default=1, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_experiments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('co_authors', models.ManyToManyField(blank=True, related_name='co_authors_experiments', to=settings.AUTH_USER_MODEL, verbose_name='Co-autores')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_experiments', to=settings.AUTH_USER_MODEL, verbose_name='Orientador')),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.PositiveIntegerField(choices=[(11, '04/10/2018 - 13:15 às 14:55'), (12, '04/10/2018 - 15:10 às 16:50'), (13, '04/10/2018 - 19:00 às 20:40'), (14, '04/10/2018 - 20:50 às 22:30'), (15, '04/10/2018 - 17:00 às 19:00'), (1, '04/10/2018 - 13:15 às 16:50'), (2, '04/10/2018 - 19:00 às 22:30')], verbose_name='Data')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='events.Event')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Inscrito'), (2, 'Presente'), (3, 'Ausente')], default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('group', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('event', 'shift')},
        ),
    ]
