# Generated by Django 2.0.6 on 2018-07-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vacancies',
            field=models.PositiveIntegerField(default=10, verbose_name='Vagas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='bio_author',
            field=models.TextField(verbose_name='Descrição do Autor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='degree',
            field=models.CharField(max_length=100, verbose_name='Titulação'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='education',
            field=models.CharField(max_length=100, verbose_name='Formação'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='event',
            name='local',
            field=models.CharField(max_length=100, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Em avaliação'), (2, 'Aprovado'), (3, 'Necessita de correções'), (4, 'Não aprovado')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=45, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='event',
            name='workload',
            field=models.TimeField(default=0, verbose_name='Carga Horária'),
        ),
    ]
