# Generated by Django 2.0.6 on 2018-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Paragráfo único com no máximo 100 palavras.', verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(help_text='Paragráfo único com no máximo 50 palavras.', verbose_name='Resumo'),
        ),
    ]
