# Generated by Django 2.1 on 2018-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='hour',
        ),
        migrations.AlterField(
            model_name='group',
            name='shift',
            field=models.PositiveIntegerField(choices=[(1, '04/10/2018 Tarde'), (2, '04/10/2018 Noite'), (11, '04/10/2018 Tarde 1'), (12, '04/10/2018 Tarde 2'), (13, '04/10/2018 Noite 1'), (14, '04/10/2018 Noite 2')], verbose_name='Data'),
        ),
    ]
