# Generated by Django 2.0.6 on 2018-08-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='degree',
            field=models.CharField(default='VII Moepex - Mostra Ensino, Pesquisa e Extensão ', max_length=100, verbose_name='Titulação'),
        ),
        migrations.AlterField(
            model_name='event',
            name='workload',
            field=models.CharField(max_length=20, verbose_name='Carga Horária'),
        ),
    ]
