# Generated by Django 2.0.6 on 2018-08-16 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='authors',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Paragráfo único com no máximo 50 palavras.', verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='authors',
            field=models.ManyToManyField(related_name='experiments', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(help_text='Paragráfo único com no máximo 100 palavras.', verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
