# Generated by Django 2.0.6 on 2018-07-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180727_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=10, verbose_name='Data Final'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_date',
            field=models.DateField(default=10, verbose_name='Data de Registro'),
            preserve_default=False,
        ),
    ]
