# Generated by Django 2.0.6 on 2018-09-05 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180831_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'verbose_name': 'Trabalho', 'verbose_name_plural': 'Trabalhos'},
        ),
        migrations.AlterField(
            model_name='event',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_events', to=settings.AUTH_USER_MODEL, verbose_name='Orientador'),
        ),
    ]
