# Generated by Django 2.1 on 2018-09-06 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180831_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'verbose_name': 'Trabalho', 'verbose_name_plural': 'Trabalhos'},
        ),
        migrations.AlterField(
            model_name='event',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_events', to=settings.AUTH_USER_MODEL, verbose_name='Orientador'),
        ),
        migrations.AlterField(
            model_name='group',
            name='shift',
            field=models.PositiveIntegerField(choices=[(11, '04/10/2018 - 13:15 às 14:55'), (12, '04/10/2018 - 15:10 às 16:50'), (13, '04/10/2018 - 19:00 às 20:40'), (14, '04/10/2018 - 20:50 às 22:30'), (1, '04/10/2018 - 13:15 às 16:50'), (2, '04/10/2018 - 19:00 às 22:30')], verbose_name='Data'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('event', 'shift')},
        ),
    ]
