# Generated by Django 2.0.6 on 2018-09-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180905_1414'),
        ('events', '0004_auto_20180905_1527'),
    ]

    operations = [
    ]
