# Generated by Django 2.0.6 on 2018-09-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180906_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.Group'),
        ),
    ]
