# Generated by Django 2.0.6 on 2018-09-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_merge_20180905_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='shift',
            field=models.PositiveIntegerField(choices=[(11, '04/10/2018 - 13:15 às 14:55'), (12, '04/10/2018 - 15:10 às 16:50'), (13, '04/10/2018 - 19:00 às 20:40'), (14, '04/10/2018 - 20:50 às 22:30'), (1, '04/10/2018 - 13:15 às 16:50'), (2, '04/10/2018 - 19:00 às 22:30')], verbose_name='Data'),
        ),
    ]
